name: Publish To Confluence
on:
  push:
  workflow_dispatch:
jobs:
  publishToConfluence:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Make Markdown File
        run: |
          mkdir docs
          cd docs
          mkdir publish_to_confluence
          cd publish_to_confluence
          echo "# Hello, World" > hello_world.md
          cd ../../
          pwd
      - name: markdown-confluence
        uses: markdown-confluence/publish-action@v5
        with:
          confluenceBaseUrl: https://katy-luttrell.atlassian.net
          confluenceParentId: 294913
          folderToPublish: "docs"
          contentRoot: /docs
          atlassianUserName: ${{ secrets.ATLASSIAN_USERNAME }}
          atlassianApiToken: ${{ secrets.ATLASSIAN_API_TOKEN }}
